=== yezideteachers/applicationAndroid/public/parcour/parcour.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="parcour">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="nom" type="xs:string" />
				<xs:element name="epreuve">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="x" type="xs:decimal" />
							<xs:element name="y" type="xs:decimal" />
							<xs:element name="question" type="xs:string" />
							<xs:element name="reponce">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="text" type="xs:string" />
										<xs:element name="correction" type="xs:boolean" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== yezideteachers/applicationAndroid/public/Serveur/src/android/parcourTipe.xml
<?xml version="1.0" encoding="UTF-8"?>
<parcour xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="parcour.xsd">
	<nom>parcourTipe</nom>
	<epreuve>
		<x>43.7159297</x>
		<y>7.2638325</y>
		<question>"Ou ete vous?"</question>
		<reponce>
			<text>"dans une fac"</texte>
			<correction>true</correction>
		</reponce>
		<reponce>
			<text>"perdu"</text>
			<correction>false</correction>
		</reponce>
	</epreuve>
	<epreuve>
		<x>43.7159297</x>
		<y>7.2638325</y>
		<question>"qui est la?"</question>
		<reponce>
			<text>"person"</texte>
			<correction>false</correction>
		</reponce>
		<reponce>
			<text>"du monde"</text>
			<correction>true</correction>
		</reponce>
	</epreuve>
</parcour>
